### PR TITLE
fix: replace `url-join` with `path.posix.join`

### LINKED ISSUE #333: Ancestor directory names containing a leading hash not supported
* Operating System: macOS High Sierra 10.13.6
* Node Version: v10.9.0
* NPM Version: 6.4.0
* webpack version: 4.17.1
* webpack-dev-middleware Version: 3.1.3

- [ ] This is a **feature** request
- [x] This is a **bug**

### For Bugs; How can we reproduce the behavior?

There are several bug reports in vue-cli repository related to this bug:

- https://github.com/vuejs/vue-cli/issues/2342
- https://github.com/vuejs/vue-cli/issues/2345
- https://github.com/vuejs/vue-cli/issues/2357

To reproduce it, run the following commands:

```
mkdir "#leadinghash"
cd "#leadinghash"
npx @vue/cli create app --default
cd app
npm run serve -- --open
```

### Expected Behavior

A hello world page.

### Actual Behavior

A blank page with following error message logged in terminal:

```
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
```

### Root Cause

It is actually a bug of `url-join`(used in [middleware.js](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/middleware.js#L54) & [util.js](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/util.js#L107)):
https://github.com/jfromaniello/url-join/issues/10

```
require('url-join').('/some/path/with/a/leading/#hash', 'index.html')
// returns '/some/path/with/a/leading#hash/index.html', the `/` before `#` is missing
```

But I think it is better to solve this issue here because:
1. Maintainers of `url-join` does not seem to have a strong willingness to fix this long-standing issue;
2. Since `url-join` is only used to join filesystem paths in `webpack-dev-middleware`, `path.posix,join` could be a sufficient replacement.

### PR DESCRIPTION
**Pull request by sodatea**
### Type

- [x] Fix

### Issues

- Fixes #333 

### SemVer

- [x] Patch

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@sodatea Happy to see it go an use a core module instead, but windows test are currently failing with this patch https://ci.appveyor.com/project/sokra/webpack-dev-middleware/build/1.0.110/job/fxenmru3b8ujigbt

File: test/tests/util.js [hunk 1]
```diff
@@ -278,41 +284,41 @@ describe('GetFilenameFromUrl', () => {
         url: '/test/windows.txt',
         outputPath: 'c:\\foo',
         publicPath: '/test',
-        // this is weird, but it's legal-ish, and what URI parsing produces
-        expected: 'c://\\foo/windows.txt'
```
Comment (michael-ciniawsky) [inline test/tests/util.js]: We need ro make sure this is valid to be removed, windows paths recognize both separators to my knowledge and this teherefore will far for some folks having `/` in their paths for whatever reason: Can you elaborate on why this can be removed please ?

Comment (sodatea) [reply test/tests/util.js]: https://github.com/webpack/webpack-dev-middleware/pull/276
> Where we might expect `c:\foo\bar` we instead get a URL-ized `c://\foo/bar`. Either works with the default path translation on Windows, though technically it's wrong.

If I understand correctly, the `//` is not indended to be preserved but now that it still works we didn’t bother removing it.

Comment (michael-ciniawsky) [reply test/tests/util.js]: Could you try with [path.normalize](https://nodejs.org/dist/latest-v10.x/docs/api/path.html#path_path_normalize_path) ?  

```js
const filename = path.posix.join(path.normalize(...))
```

Comment (sodatea) [reply test/tests/util.js]: ping @michael-ciniawsky

Comment (michael-ciniawsky) [reply test/tests/util.js]: Paths are not URLs there must be a reason why `url-join` was used here instead. I didn't write this code so I'm not sure if 'this only handles file paths'  renders 💯 true.  I think the issue with `path.nomalize` was, that we would need to use the `path.posix` variant instead

```diff
- const filename = path.posix.join(path.normalize(...), ...)
+ const filename = path.posix.join(path.posix.normalize(...), ...)
```

But leave it for now until we know how to proceed here in general :)

File: lib/util.js [hunk 2]
```diff
@@ -1,10 +1,10 @@
 'use strict';
 
+const path = require('path');
 const { parse } = require('url');
 const querystring = require('querystring');
 const pathabs = require('path-is-absolute');
```
Comment (michael-ciniawsky) [inline lib/util.js]: This should be gone by now https://github.com/webpack/webpack-dev-middleware/pull/335. Could you rebase with the PR with latest `master` to ensure we won't get a bad merge here please ?

Comment (sodatea) [reply lib/util.js]: Done 😄

**Comment by michael-ciniawsky** [comment]
@sodatea Since this removes a dependency could you update the lockfile? Otherwise this should this is ready to land

File: lib/util.js (hunk 2 above)
Comment (michael-ciniawsky) [reply lib/util.js]: Doesn't seemed to be the case the line is still there (?)

Comment (sodatea) [reply lib/util.js]: Ahh, sorry, forgot to `push -f` 😅
Should be fixed now.
