### PR TITLE
fix: improve URL handling in getRequestURL function

### LINKED ISSUE #2303: v8 does not respect req.url
### Have you used AI?

No

### Bug Description

In v8 of webpack-dev-middleware, the middleware is trying to serve `req.originalUrl` when it should be trying to serve `req.url`. This is happening because of [this logic](https://github.com/webpack/webpack-dev-middleware/blob/main/src/utils.js#L316-L318). This breaks usage when used with URL rewrites, which is common with middleware like [connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback/tree/main).

### Link to Minimal Reproduction and step to  reproduce

https://github.com/Methuselah96/webpack-dev-middleware-rewrite

Steps:
1. Run `npm install`
2. Run `npm run watch`
3. Navigate to http://localhost:3000/some-path
4. Observe "Cannot GET /some-path" error

### Expected Behavior

The dev middleware should respect the `req.url` and serve `/index.html` instead of returning an error

### Actual Behavior

The dev middleware tries to load `/some-path` and fails

### Environment

```shell
System:
    OS: Windows 11 10.0.26200
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500
    Memory: 7.01 GB / 31.65 GB
  Binaries:
    Node: 24.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.9.2 - C:\Program Files\nodejs\yarn.CMD
    npm: 11.6.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.9 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 146.0.7680.165
    Edge: Chromium (140.0.3485.54)
    Firefox: 149.0 - C:\Program Files\Mozilla Firefox\firefox.exe
    Internet Explorer: 11.0.26100.8115
  Packages:
    html-webpack-plugin: ^5.6.6 => 5.6.6 
    webpack: ^5.105.4 => 5.105.4 
    webpack-cli: ^7.0.2 => 7.0.2 
    webpack-dev-middleware: ^8.0.2 => 8.0.2
```

### Is this a regression?

Yes (please specify version below)

### Last Working Version

v7.4.5

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bjohansebas**
**Summary**

fixed #2303 

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**If relevant, what needs to be documented once your changes are merged or what have you already documented?**

**Use of AI**

yes!

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -312,9 +312,27 @@ function getRequestURL(req) {
...
+      if (
+        req.url === req.originalUrl ||
+        (typeof req.url !== "undefined" &&
+          decodeURI(req.originalUrl) === req.url)
+      ) {
+        return req.originalUrl;
+      }
+    } catch {
+      // decodeURI can throw on malformed sequences, fall through
+    }
```
Comment (alexander-akait) [inline src/utils.js:326]: It this problem only for fastlify? `decodeURI` is not fast, so it is bad for performance

Comment (bjohansebas) [reply src/utils.js:326]: Yep, it's unique to Fastify, or at least I don't remember Express having the same issue. Fastify uses its own logic instead of using decodeURI https://github.com/fastify/middie/pull/245

Comment (alexander-akait) [reply src/utils.js:326]: in this case let's add a pseudo API for fastify here and implement this logic only for fastify, don't want to lose perfomance for other frameworks

Comment (bjohansebas) [reply src/utils.js:326]: I’m not sure what steps to follow. It would be great if Fastify exposed something like `req.raw` on the request (since it currently doesn’t, which is a bit odd—but I’m not a Fastify expert). That way we could quickly detect it, since neither Express nor Connect have that property. However, Hono also has a `getURL` method, and since our logic checks `getURL`, it would never reach the fallback logic using `req.raw`.

Now the real issue is that Fastify *does* decode `req.url`, while Express and others don’t.

We could add logic like this:

```js
if (typeof req.originalUrl !== "undefined") {
  if (req.url === req.originalUrl) {
    return req.originalUrl;
  }

  // Some frameworks can expose decoded req.url while keeping
  // encoded req.originalUrl.
  if (typeof req.url !== "undefined" && req.originalUrl.includes("%")) {
    try {
      if (decodeURI(req.originalUrl) === req.url) {
        return req.originalUrl;
      }
    } catch {
      // Ignore malformed URI sequences and fall back to req.url.
    }
  }
}
```

Or we could create a wrapper for Fastify, but I’m not sure how reliable it would be to correctly detect that Fastify is running underneath.

Another option would be to open an issue in `@fastify/express` to have them expose `raw`, so we can better detect Fastify internally.

What would you recommend without hurting performance too much?

I’m thinking about other ways to detect it—I’ll see what I come up with by tomorrow night

Comment (alexander-akait) [reply src/utils.js:326]: I see the problem... Made refactor to use `req.id` to apply this logic only for fastify

Comment (alexander-akait) [reply src/utils.js:326]: > Or we could create a wrapper for Fastify, but I’m not sure how reliable it would be to correctly detect that Fastify is running underneath.

I think in future we can do it and implement built-in fastify support without the fastify-express layer, but to be honestly fastify is not very popular, so I think we will use fastify-express until it was supported, when it will be deprecated we will implement own wrapper

> Another option would be to open an issue in @fastify/express to have them expose raw, so we can better detect Fastify internally.

It will be fine, let's try it, if it will be fixed we will revert this code and will use `raw`, so feel free to open an issue

**Review by alexander-akait — APPROVED** [review]

File: src/utils.js (hunk 1 above)
Comment (bjohansebas) [reply src/utils.js:326]: I didn’t know `req.id` existed, that’s new to me.
