### PR TITLE
fixes #258: skip compilers with no publicPath

### LINKED ISSUE #258: Crash when server config (server/client multi config) does not contain config.output.publicPath.
* Operating System: Windows 10
* Node Version: 9.2.0
* NPM Version: 5.5.1
* webpack version: 3.10.0
* webpack-dev-middleware Version: 2.0.5

- [ ] This is a **feature** request
- [X] This is a **bug**

### Code

A boilerplate project which reproduces this bug is at: https://github.com/faceyspacey/universal-demo
(after upgrading webpack + webpack-dev-middleware to latest)

```js
// client config
  output: {
    filename: "[name].js",
    chunkFilename: "[name].js",
    path: path.resolve(__dirname, "../buildClient"),
    publicPath: "/static/",
  },

// server config
  output: {
    path: output,
    filename: "[name].js",
    libraryTarget: "commonjs2",
  },
```

### Expected Behavior
Previously, the client config has been the first ([client, server]) so the client config publicPath was chosen. I'm not familiar with multi-compiler configurations beyond the use of webpack-hot-server-middleware, so I'm not sure what would be expected beyond this case.

### Actual Behavior
Server crashes:
```js
TypeError: Cannot read property 'indexOf' of undefined
    at getPaths (/mnt/c/Users/threehams/workspace/univ-demo/node_modules/webpack-dev-middleware/lib/util.js:27:30)
    at getFilenameFromUrl (/mnt/c/Users/threehams/workspace/univ-demo/node_modules/webpack-dev-middleware/lib/util.js:60:40)
    at middleware (/mnt/c/Users/threehams/workspace/univ-demo/node_modules/webpack-dev-middleware/lib/middleware.js:26:20)
...
```

### For Bugs; How can we reproduce the behavior?
* Clone https://github.com/faceyspacey/universal-demo
* Update webpack to 3.10.0, webpack-dev-middleware to 2.0.5
* `npm start`
* Visit localhost:3000 (crash occurs at runtime)

### PR DESCRIPTION
**Pull request by threehams**
**What kind of change does this PR introduce?**
Fixes #258.

**Did you add tests for your changes?**
Yes, both 200 and 404 cases.

**Summary**
This fixes a crash when accessing a path outside of publicPath, in a multi-compiler setup, when one of the compiler configs does not include a publicPath. This can occur when using universal rendering through https://github.com/60frames/webpack-hot-server-middleware.

**Does this PR introduce a breaking change?**
No.

**Other information**

### CODE REVIEW

**Comment by shellscape** [comment]
(removed labels as they apply to issues rather than PRs)

File: lib/util.js [hunk 1]
```diff
@@ -21,22 +21,24 @@ function getPaths(publicPath, compiler, url) {
...
-    && compilers[i].options.output.publicPath;
-
-      if (compilerPublicPath.indexOf('/') === 0) {
-        compilerPublicPathBase = compilerPublicPath;
-      } else {
-        // handle the case where compilerPublicPath is a URL with hostname
-        compilerPublicPathBase = parse(compilerPublicPath).pathname;
-      }
+        && compilers[i].options.output
+        && compilers[i].options.output.publicPath;
```
Comment (shellscape) [inline lib/util.js]: strange whitespace goings on here. the formatting of the original code looks off by a tab-space, but please try to avoid modifying whitespace in PRs.

File: test/tests/server.js [hunk 2]
```diff
@@ -245,6 +246,28 @@ describe('Server', () => {
...
+      app.use(instance);
+      listen = listenShorthand(done);
+    });
+    after(close);
+
+    it('request to bundle file', (done) => {
+      request(app).get('/static/foo.js').expect(200, done);
+    });
+
+    it('request to non-public path', (done) => {
```
Comment (shellscape) [inline test/tests/server.js]: should also test for a non-existent resource on a valid public path for thoroughness. eg. `/static/foo.js`

**Comment by threehams** [comment]
Done. The intentional un-indented multi-line conditional is a new one to me.

**Comment by shellscape** [comment]
Yeah that's a remnant of pre-Node-v4 support. I've got a `TODO` to audit the code for stuff like that in the coming weeks. Thanks for getting those changes in.

**Comment by elado** [comment]
Thanks for the fix ❤️! When is it expected to be released?

**Comment by roastlechon** [comment]
@shellscape @elado also would like to know when this will be released

**Comment by shellscape** [comment]
How about now.

**Comment by roastlechon** [comment]
<3 !!!!!!!
